/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: me_blender (https://sketchfab.com/me_blender)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/samsung-s24-ultra-f642a96e26974e649da6dc64129beee7
Title: Samsung S24 Ultra
*/

import * as THREE from 'three';
import React, { useEffect, useRef } from "react";
import { useGLTF, useTexture,useVideoTexture } from "@react-three/drei";

 function Model(props) {
  const { nodes, materials } = useGLTF('/models/samsung_s24_ultra.glb')

  const texture = useTexture(props.item.img);

    useEffect(() => {
      Object.entries(materials).map((material) => {
        // these are the material names that can't be changed color
        if (
          material[0] !== "zFdeDaGNRwzccye" &&
          material[0] !== "ujsvqBWRMnqdwPx" &&
          material[0] !== "hUlRcbieVuIiOXG" &&
          material[0] !== "jlzuBkUzuJqgiAK" &&
          material[0] !== "xNrofRCqOXXHVZt"
        ) {
          material[1].color = new THREE.Color(props.item.color[0]);
        }
        material[1].needsUpdate = true;
      });
    }, [materials, props.item]);

    const videoTexture = useVideoTexture('/assets/videos/explore.mp4', {
        loop: true,
        muted: true,
        autoplay: true,
        crossOrigin: 'Anonymous',
      });
    
    
      useEffect(() => {
        if (videoTexture) {
          const video = videoTexture.image;
          video.play().catch((error) => {
            console.error('Error playing video:', error);
          });
        }
      }, [videoTexture]);
  return (
    <group {...props} dispose={null} scale={[0.6, 0.6 ,0.6]}>
    <group position={[0, 0, 0]} scale={1.856}>
      <group position={[-0.012, -0.134, 0]} scale={[0.539, 0.539, 0.061]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Silver}
        >

        </mesh>
      </group>
      <group position={[-0.032, -0.081, 0]} scale={[0.539, 0.539, 0.07]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.Screen}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.Silver}
        position={[-0.371, 0.821, 0.05]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.113, 0.051, 0.113]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials.Silver}
        position={[-0.371, 0.554, 0.05]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.113, 0.051, 0.113]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.Silver}
        position={[-0.371, 0.292, 0.05]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.113, 0.051, 0.113]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.Silver}
        position={[-0.131, 0.56, 0.055]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.072, 0.032, 0.072]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.Silver}
        position={[-0.131, 0.817, 0.055]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.072, 0.032, 0.072]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials['Material.001']}
        position={[-0.373, 0.822, 0.069]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.094, 0.004, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials['Material.001']}
        position={[-0.373, 0.558, 0.069]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.094, 0.004, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials['Material.001']}
        position={[-0.373, 0.296, 0.069]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.094, 0.004, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_27.geometry}
        material={materials['Material.001']}
        position={[-0.13, 0.818, 0.07]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.061, 0.003, 0.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_29.geometry}
        material={materials['Material.001']}
        position={[-0.133, 0.56, 0.07]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.061, 0.003, 0.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={materials['Material.004']}
        position={[-0.373, 0.821, 0.103]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.096, 0.004, 0.096]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_33.geometry}
        material={materials['Material.004']}
        position={[-0.371, 0.556, 0.103]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.098, 0.004, 0.098]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_35.geometry}
        material={materials['Material.004']}
        position={[-0.373, 0.291, 0.103]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.096, 0.004, 0.096]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_37.geometry}
        material={materials['Material.004']}
        position={[-0.131, 0.818, 0.085]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.064, 0.003, 0.064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_39.geometry}
        material={materials['Material.004']}
        position={[-0.131, 0.56, 0.085]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.064, 0.003, 0.064]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_41.geometry}
        material={materials.Silver}
        position={[0, -1.274, 0.003]}
        scale={[0.074, 0.032, 0.003]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_43.geometry}
        material={materials.Flash}
        position={[-0.131, 0.688, 0.082]}
        scale={[0.028, 0.028, 0.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_45.geometry}
        material={materials.Lens}
        position={[-0.375, 0.823, 0.082]}
        scale={[0.032, 0.032, 0.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47.geometry}
        material={materials.Lens}
        position={[-0.375, 0.556, 0.082]}
        scale={[0.032, 0.032, 0.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_49.geometry}
        material={materials.Lens}
        position={[-0.375, 0.295, 0.082]}
        scale={[0.039, 0.039, 0.023]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_51.geometry}
        material={materials.Lens}
        position={[-0.133, 0.556, 0.082]}
        scale={[0.022, 0.022, 0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_53.geometry}
        material={materials.Screen}
        position={[-0.375, 0.825, 0.067]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.049, 0.028, 0.049]}
      >

            <meshStandardMaterial
              map={videoTexture} // Video as the base texture
              transparent={true} // Enable transparency
            />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_55.geometry}
        material={materials.Screen}
        position={[-0.375, 0.555, 0.067]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.049, 0.028, 0.049]}
      />
           
    
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_57.geometry}
        material={materials.Screen}
        position={[-0.375, 0.295, 0.067]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.055, 0.031, 0.055]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_59.geometry}
        material={materials.Screen}
        position={[-0.133, 0.558, 0.067]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.033, 0.019, 0.033]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_61.geometry}
        material={materials['Material.001']}
        position={[-0.507, 0.057, 0]}
        scale={[0.105, 0.084, 0.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_63.geometry}
        material={materials['Material.001']}
        position={[0.469, -1.213, -0.001]}
        scale={[0.035, 0.102, 0.026]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_65.geometry}
        material={materials['Material.001']}
        position={[-0.507, 0.427, 0]}
        scale={[0.105, 0.152, 0.019]}
      />
    </group>
  </group>
  )
}

export default Model;
useGLTF.preload('/models/samsung_s24_ultra.glb')